name: vedanta_frontend
description: "A new Flutter project."
publish_to: "none"
version: 0.2.0

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  audio_service: ^0.18.13
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.8.0
  flutter_keyboard_visibility: ^6.0.0
  flutter_local_notifications: ^17.1.2
  flutter_markdown: ^0.7.1
  flutter_polygon: ^0.3.0+2
  http: ^1.2.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  just_audio: ^0.9.38
  jwt_decode: ^0.3.1
  numberpicker: ^2.1.2
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  provider: ^6.1.2
  record: ^5.0.0
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  sqflite: ^2.3.3+1
  youtube_player_flutter: ^8.1.2
  path: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/
    - lib/assets/images/
    - lib/assets/images/icons/

  fonts:
    - family: NotoSansDevanagari
      fonts:
        - asset: lib/assets/fonts/NotoSansDevanagari.ttf
    - family: GauraTimesRegular
      fonts:
        - asset: lib/assets/fonts/Gaura-Times-Regular.ttf
          weight: 600
