name: vedanta_frontend
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  alarm: ^3.1.4
  audio_service: ^0.18.13
  flutter:
    sdk: flutter
  flutter_keyboard_visibility: ^6.0.0
  flutter_markdown: ^0.7.1
  http: ^1.2.1
  intl: ^0.19.0
  just_audio: ^0.9.38
  jwt_decode: ^0.3.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/
    - lib/assets/images/
    - lib/assets/images/icons/

  fonts:
    - family: NotoSansDevanagari
      fonts:
        - asset: lib/assets/fonts/NotoSansDevanagari.ttf
    - family: GauraTimesRegular
      fonts:
        - asset: lib/assets/fonts/Gaura-Times-Regular.ttf
          weight: 600
